# Problem 2 :
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def answer():
    sum = 0
    n1 = 1
    n2 = 1
    temp = 0
    while n2 < 4000000:
        if n2 % 2 == 0:
            sum += n2
        temp = n1
        n1 = n2
        n2 = temp + n1
    print(f"The sum of all fibonacci numbers below 4 000 000 is {sum}")

if __name__ == "__main__":
    answer()